### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by cocych** [calbear47/colorApp2#7]
I wanted to update a previously added piece of artwork...I am not able to do so because of a Bad Gateway.

**Comment by calbear47** [comment]
I've never experience so much trouble with this server,I'm reboot and take care of that.

**Comment by cocych** [comment]
Thanks honey!



*Cynthia Christine *


*The Colors of Cynthia Christine*

*www.colorsofcynthiachristine.com <http://www.colorsofcynthiachristine.com>*
*www.etsy.com/shop/ColorsOfCynthiaC
<http://www.etsy.com/shop/ColorsOfCynthiaC>  *
www.fineartamerica.com/profiles/cynthia-christine.html

*925-386-6108*

*         ColorsOfCynthiaC on Etsy*

*                   Cynthia Christine on Fine Art America*

*                               Colors Of Cynthia Christine *


*                                                  on  Instagram, Facebook,
Pinterest*

*“Gratitude is the real treasure *

*                      God wants us to find, *

*                                        because it isn't the pot of gold  *


*                                                     but the rainbow that
colors our world.”
                                                  -Richelle Goodrich*

**Comment by calbear47** [comment]
Btw, it's back up.

**Comment by cocych** [comment]
Yup, just went on and was able to delete the piece of artwork until I can
re-list it! Thanks!



*Cynthia Christine *


*The Colors of Cynthia Christine*

*www.colorsofcynthiachristine.com <http://www.colorsofcynthiachristine.com>*
*www.etsy.com/shop/ColorsOfCynthiaC
<http://www.etsy.com/shop/ColorsOfCynthiaC>  *
www.fineartamerica.com/profiles/cynthia-christine.html

*925-386-6108*

*         ColorsOfCynthiaC on Etsy*

*                   Cynthia Christine on Fine Art America*

*                               Colors Of Cynthia Christine *


*                                                  on  Instagram, Facebook,
Pinterest*

*“Gratitude is the real treasure *

*                      God wants us to find, *

*                                        because it isn't the pot of gold  *


*                                                     but the rainbow that
colors our world.”
                                                  -Richelle Goodrich*
