### ISSUE TITLE
Insecure Website

### ISSUE THREAD

**Issue by cocych** [calbear47/colorApp2#8]
I can't open my website on Firefox because it is "insecure", Safari warns you this website is insecure but allows me to open it. It has been happening for two days that I know of. I attached a screen shot for the Firefox. 
![screen shot 2017-06-11 insecure website](https://user-images.githubusercontent.com/26388361/27014124-fa073b80-4ea6-11e7-8d94-f893bb5256b7.jpg)

**Comment by calbear47** [comment]
I should be able to get to this today. Thanks!

**Comment by cocych** [comment]
Great.....if there is a time to connect otherwise, I'd love to catch up
with you.....



*Cynthia Christine *


*The Colors of Cynthia Christine*

*www.colorsofcynthiachristine.com <http://www.colorsofcynthiachristine.com>*
*www.etsy.com/shop/ColorsOfCynthiaC
<http://www.etsy.com/shop/ColorsOfCynthiaC>  *
www.fineartamerica.com/profiles/cynthia-christine.html

*925-386-6108*

*         ColorsOfCynthiaC on Etsy*

*                   Cynthia Christine on Fine Art America*

*                               Colors Of Cynthia Christine *


*                                                  on  Instagram, Facebook,
Pinterest*

*“Gratitude is the real treasure *

*                      God wants us to find, *

*                                        because it isn't the pot of gold  *


*                                                     but the rainbow that
colors our world.”
                                                  -Richelle Goodrich*

**Comment by calbear47** [comment]
Renewed Certs
